spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: lzr961202
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500

my:
  name: runyi
  age: 24
  uuid: ${random.uuid}
  value: ${random.value}
  max: ${random.int(10)}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
  server:
    port: 9001
